### ISSUE TITLE
Using multiple directives in same page doesn't work

### ISSUE THREAD

**Issue by jerkovicl** [mojotech/angular-ui-instagram#2]
Is it possible to make it work with isolated scope?

**Comment by aesnyder** [comment]
Hm, I'm not sure. I haven't tried, have you?

**Comment by aesnyder** [comment]
Oh you're right it looks like it wont due to a non-isolated scope. Want to open a PR?

**Comment by jerkovicl** [comment]
yeah i have tried but i am still learning angular so maybe i did something wrong

**Comment by jerkovicl** [comment]
```
.directive('uiInstagram', function () {
        return {
            restrict: 'EA',
            **scope: {
                userId: '@',
                clientId: '@'
            }**,
            controller: function ($scope, $attrs, Instagram) {
                $scope.grams = [];
                return Instagram.get($attrs.userId, $attrs.clientId, function (grams) {
                    return $scope.grams = grams;
                });
            }
        };
    });

}).call(this);
```

**i added bolded part to directive but it doesnt work for me, according to my understanding this should create isolate scope and bind those 2 attributes to corresponding html attributes of directive**

**Comment by jerkovicl** [comment]
debugging via Angular Batarang i see 2 different scopes with proper data from endpoints, but rendered html page is blank
